// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Real per-platform options are below (generated by flutterfire).
  static bool get isConfigured => true;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFdn5iBZFRxl2BTdWPRzjF7iRAOZessxk',
    appId: '1:453231448530:web:ab1f667b98d7d1621e380b',
    messagingSenderId: '453231448530',
    projectId: 'im-done-17215',
    authDomain: 'im-done-17215.firebaseapp.com',
    storageBucket: 'im-done-17215.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhu0fL8q7SRLw-Z1mYgLxsrkxBvQ-Cb-w',
    appId: '1:453231448530:android:bc3d448b23f5ae7d1e380b',
    messagingSenderId: '453231448530',
    projectId: 'im-done-17215',
    storageBucket: 'im-done-17215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKiLQEuZB3Fo-HoBJdQTul0XAogYh4dVI',
    appId: '1:453231448530:ios:16f7e5153389d6c71e380b',
    messagingSenderId: '453231448530',
    projectId: 'im-done-17215',
    storageBucket: 'im-done-17215.firebasestorage.app',
    iosBundleId: 'me.imdone.app',
  );
}
