#!/usr/bin/env python3
"""The translation pipeline. Every language is ONE table, l10n/<code>.json,
keyed exactly like l10n/en.json; this script turns them all into Dart
(lib/l10n/tables.g.dart) and REFUSES a table that is missing a key, has an
empty value, or drops a {placeholder} the English carries — so a language
cannot half-exist and a screen can never fall back to English by accident.

Run:  python3 tool/gen_l10n.py        (also run by the tests in CI)
"""
import json, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'l10n'
OUT = ROOT / 'lib' / 'l10n' / 'tables.g.dart'
PUSH_OUT = ROOT / 'push-worker' / 'src' / 'push-strings.g.json'
PUSH_KEYS = ['pushAdded', 'pushJoined', 'pushClaimed', 'pushClaimedBody', 'pushConfirmed', 'pushRejected']
PLACEHOLDER = re.compile(r'\{[a-zA-Z]+\}')

def dart_str(s: str) -> str:
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$').replace('\n', '\\n') + "'"

def main() -> int:
    en = json.loads((SRC / 'en.json').read_text(encoding='utf-8'))
    tables = {}
    problems = []
    for path in sorted(SRC.glob('*.json')):
        code = path.stem
        t = json.loads(path.read_text(encoding='utf-8'))
        missing = sorted(set(en) - set(t)); extra = sorted(set(t) - set(en))
        if missing: problems.append(f'{code}: missing keys {missing}')
        if extra: problems.append(f'{code}: unknown keys {extra}')
        for k, v in en.items():
            if k not in t: continue
            if isinstance(v, list):
                if not (isinstance(t[k], list) and len(t[k]) == len(v) and all(isinstance(x, str) and x.strip() for x in t[k])):
                    problems.append(f'{code}.{k}: must be a list of {len(v)} non-empty strings')
                continue
            if not isinstance(t[k], str) or not t[k].strip():
                problems.append(f'{code}.{k}: empty')
                continue
            want = set(PLACEHOLDER.findall(v)); have = set(PLACEHOLDER.findall(t[k]))
            if want != have: problems.append(f'{code}.{k}: placeholders {sorted(want)} became {sorted(have)}')
        tables[code] = t
    if problems:
        print('l10n pipeline refused:\n  ' + '\n  '.join(problems), file=sys.stderr)
        return 1
    lines = ['// GENERATED by tool/gen_l10n.py from l10n/*.json — do not edit by hand.', '// ignore_for_file: type=lint', '', "import 'strings.dart';", '']
    for code, t in tables.items():
        ident = 'l10n' + code.capitalize()
        lines.append(f'const {ident} = L10n(')
        for k, v in en.items():
            val = t[k]
            if isinstance(val, list):
                lines.append(f'  {k}: [{", ".join(dart_str(x) for x in val)}],')
            else:
                lines.append(f'  {k}: {dart_str(val)},')
        lines.append(');\n')
    lines.append('/// Every language the app can display, by ISO 639-1 code.')
    lines.append('const Map<String, L10n> l10nTables = {')
    for code in tables: lines.append(f"  '{code}': l10n{code.capitalize()},")
    lines.append('};')
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    # The push worker speaks the same tables: notifications between phones
    # come out of this file, never out of strings typed into the worker.
    PUSH_OUT.write_text(json.dumps({c: {k: t[k] for k in PUSH_KEYS} for c, t in tables.items()}, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)} and {PUSH_OUT.relative_to(ROOT)} with {len(tables)} languages: {", ".join(tables)}')
    return 0

if __name__ == '__main__':
    sys.exit(main())
