// Pure decisions, unit-tested: who gets told what, in which language.

export const KINDS = ['added', 'joined', 'claimed', 'confirmed', 'rejected'];

// Generated by tool/gen_l10n.py from l10n/*.json — the app's own
// translation pipeline. Add a language there, never here.
import STRINGS from './push-strings.g.json' with { type: 'json' };

const fill = (s, args) => Object.entries(args).reduce((acc, [k, v]) => acc.replaceAll(`{${k}}`, v), s);

export function message(kind, lang, title, who) {
  const t = STRINGS[lang] ?? STRINGS.en;
  const args = { who, title };
  switch (kind) {
    case 'added': return { title: fill(t.pushAdded, args), body: title };
    case 'joined': return { title: fill(t.pushJoined, args), body: title };
    case 'claimed': return { title: fill(t.pushClaimed, args), body: fill(t.pushClaimedBody, args) };
    case 'confirmed': return { title: fill(t.pushConfirmed, args), body: title };
    case 'rejected': return { title: fill(t.pushRejected, args), body: title };
    default: return { title, body: title };
  }
}

/**
 * Which member uids may be told, given who is asking. Returns [] when the
 * request is not one the product allows — the sender is not a member, or
 * asks for a recipient the kind does not permit.
 *
 *  added     creator → the person just added (must be a member now)
 *  joined    new member → the creator
 *  claimed   member → the creator
 *  confirmed / rejected   creator → everyone else (rejected: the claimant only, if named)
 */
export function recipients(kind, task, senderUid, toUid) {
  const members = task.memberUids ?? [];
  if (!members.includes(senderUid)) return [];
  const owner = task.ownerUid;
  switch (kind) {
    case 'added':
      return senderUid === owner && toUid && toUid !== owner && members.includes(toUid) ? [toUid] : [];
    case 'joined':
    case 'claimed':
      return senderUid !== owner ? [owner] : [];
    case 'confirmed':
      return senderUid === owner ? members.filter((u) => u !== owner) : [];
    case 'rejected':
      if (senderUid !== owner) return [];
      return toUid && members.includes(toUid) && toUid !== owner ? [toUid] : members.filter((u) => u !== owner);
    default:
      return [];
  }
}
